name: ReliableStereoMatcher
dependencies:
  - python=3.7
  - pip=20.0.2
  - pip:
    - bitarray
    - jupyter
    - matplotlib
    - numpy
    - opencv-contrib-python==4.1.2.30
    - opencv-python==4.1.1.26
    - tensorflow==2.1.0
    - tensorflow-addons==0.9.0
    - tensorflow-probability==0.9.0
    - tqdm
